### ISSUE TITLE
Identifiers need to be all lowercase

### ISSUE THREAD

**Issue by darkshade9** [packetflinger/q2rcon#1]
Hello,

Thanks for writing this.  I found a small bug(?) in that the server `identifier` must be lowercase, else it will return `can't resolve alias`

Works:
```
password {
  identifier: "rektek"
  secret: "zzz"
}

server {
  identifier: "rektek"
  address: "192.168.0.42:27915"
  rcon_password: "rektek"
}
```

Doesn't work:
```
password {
  identifier: "rektek"
  secret: "zzz"
}

server {
  identifier: "Rektek"
  address: "192.168.0.42:27915"
  rcon_password: "rektek"
}
```

**Comment by joe0x04** [comment]
Hi!
Oops, I do everything in lower case, so I didn't test that well enough. It's always fun finding out someone else uses your little life-simplifying utils. Update pushed, I'll publish a new release after work today.

Thanks for opening up the issue!

**Comment by darkshade9** [comment]
Great, thank you @joe0x04 !
